language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install: sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pylama

script: python -m pytest --cov=src/luminol/ src/luminol/tests/
after_script: python -m pylama -i E501,E402,E0602 src/luminol/ || true
